version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - /c/Users/Paul Linke/Herd/kundenverwaltung/database:/var/www/html/database
    environment:
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    command: >
      sh -c "
      if [ ! -f /var/www/html/database/database.sqlite ]; then
        mkdir -p /var/www/html/database &&
        touch /var/www/html/database/database.sqlite &&
        chown -R www-data:www-data /var/www/html/database;
      fi &&
      php artisan migrate --force &&
      apache2-foreground
      "

volumes:
  sqlite_data:
